# Generated by Django 5.0 on 2024-09-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hood',
            field=models.CharField(max_length=100),
        ),
    ]
