# Generated by Django 5.0 on 2024-11-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_name_en', models.CharField(max_length=100, null=True)),
                ('customer_name_ru', models.CharField(max_length=100, null=True)),
                ('customer_name_uz', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_name_en', models.CharField(max_length=100, null=True)),
                ('company_name_ru', models.CharField(max_length=100, null=True)),
                ('company_name_uz', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('position_en', models.CharField(max_length=100, null=True)),
                ('position_ru', models.CharField(max_length=100, null=True)),
                ('position_uz', models.CharField(max_length=100, null=True)),
                ('review_text', models.TextField()),
                ('review_text_en', models.TextField(null=True)),
                ('review_text_ru', models.TextField(null=True)),
                ('review_text_uz', models.TextField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='customer_reviews_logos/')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('question_ru', models.CharField(max_length=255, null=True)),
                ('question_uz', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('answer_uz', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('text_ru', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('text_uz', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('statistic', models.IntegerField(default=0, verbose_name='Statistic')),
            ],
            options={
                'verbose_name': 'Our history and achievements',
                'verbose_name_plural': 'Our history and achievements',
            },
        ),
        migrations.CreateModel(
            name='MainCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='main_carousel_images/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Main Carousel Item',
                'verbose_name_plural': 'Main Carousel Items',
            },
        ),
        migrations.CreateModel(
            name='ProductsCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='products_carousel_images/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Products Carousel Item',
                'verbose_name_plural': 'Products Carousel Items',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_uz', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Showcase Category',
                'verbose_name_plural': 'Showcase Categories',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('image_one', models.ImageField(upload_to='showcase/')),
                ('image_two', models.ImageField(upload_to='showcase/')),
                ('publish', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_products', to='contentmanagement.showcasecategory')),
            ],
            options={
                'verbose_name': 'Showcase Product',
                'verbose_name_plural': 'Showcase Products',
            },
        ),
    ]
