"""
Django settings for elima project.

Generated by 'django-admin startproject' using Django 3.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%hgmet4-2x)@=gl-f=(bl+jr1dmjt1%trz4_8tstq8gmkmot@2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [    
    'uzelima.com', 
    'www.uzelima.com', 
    'https://uzelima.com', 
    'http://uzelima.com', 
    'https://www.uzelima.com',
    'http://www.uzelima.com',
    '127.0.0.1:8000/ru/',
    '127.0.0.1:8000/en/',
    '127.0.0.1:8000/uz/',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://uzelima.com',
    'http://uzelima.com',
    'https://www.uzelima.com',
    'http://www.uzelima.com'
]

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'ckeditor',
    'ckeditor_uploader',
    'django_filters',
    'modeltranslation',
    'pages',
    'blog',
    'store',
    'contentmanagement',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'elima.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'elima.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'default_db',
        'USER': 'gen_user',
        'PASSWORD': 'Rp%BSr-FmC34e/',
        'HOST': 'aa508f4113c1faadf53e0605.twc1.net',
        'PORT': '3306',

        # Optional extras:
        'CONN_MAX_AGE': 600,        # persistent connections
        'OPTIONS': {
            # If Timeweb provides an SSL CA cert:
            'ssl': {
                'ca': '/home/app/.cloud-certs/root.crt',
            },
            'ssl_mode': 'VERIFY_IDENTITY',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian'),
    ('uz', 'Uzbek'),
]

LANGUAGE_CODE = 'ru'

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# In your Timeweb env vars set:
#   AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
#   AWS_STORAGE_BUCKET_NAME, AWS_S3_ENDPOINT_URL, AWS_S3_REGION_NAME

AWS_ACCESS_KEY_ID        = '5GSOITR7DPH24PKBJ26M'
AWS_SECRET_ACCESS_KEY    = 'dJmhJQmO5vD8nuqRuUhMxCCf3zPhHBL3RvcHqcI9'
AWS_STORAGE_BUCKET_NAME  = '46c13bbf-2ceafdc8-49d7-49df-aeb8-45a960c556aa'
AWS_S3_ENDPOINT_URL      = 'https://s3.twcstorage.ru'       # https://s3.twcstorage.ru
AWS_S3_REGION_NAME       = 'ru-1'    # ru-1
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE  = 'path'

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
# tell django-storages to use our custom S3 endpoint
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/'

# local fallback (e.g. for DEBUG)

STATICFILES_DIRS = [str(BASE_DIR.joinpath('static'))]
STATIC_ROOT = str(BASE_DIR.joinpath('staticfiles'))

# MEDIA FILES (served by Django + WhiteNoise or your webserver)
MEDIA_URL = '/media/'
MEDIA_ROOT = str(BASE_DIR.joinpath('media'))

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_RESTRICT_BY_USER = True

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 'auto',
        'remove_dialog_tabs': 'image:advanced;link:advanced',
    }
}

# Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "Elima",
    "site_brand": "Панель управления",
    "welcome_sign": "Elima",
    "site_logo": "img/company_logo_.png",
    "site_header": "Elima Dashboard",
    "show_ui_builder": True,
    "order_with_respect_to": ["pages", "contentmanagement", "store", "blog", "auth"],
}