"""
Django settings for elima project.

Generated by 'django-admin startproject' using Django 3.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%hgmet4-2x)@=gl-f=(bl+jr1dmjt1%trz4_8tstq8gmkmot@2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [    
    'uzelima.com', 
    'www.uzelima.com', 
    'https://uzelima.com', 
    'http://uzelima.com', 
    'https://www.uzelima.com',
    'http://www.uzelima.com',
    '127.0.0.1:8000/ru/',
    '127.0.0.1:8000/en/',
    '127.0.0.1:8000/uz/',
    '127.0.0.1',
    'sardorbek-dev-elima-7b68.twc1.net',
    '81.200.153.64'
]

CSRF_TRUSTED_ORIGINS = [
    'https://uzelima.com',
    'http://uzelima.com',
    'https://www.uzelima.com',
    'http://www.uzelima.com'
]

CORS_ALLOW_ALL_ORIGINS = True

# ─── APPLICATIONS ───────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'storages',
    'ckeditor',
    'ckeditor_uploader',
    'django_filters',


    # your apps
    'pages',
    'blog',
    'store',
    'contentmanagement',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # fallback static serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'elima.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # add project-level template dirs here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'context_processors.export_vars',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'elima.wsgi.application'

# ─── DATABASE (MySQL with SSL) ─────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ─── PASSWORD VALIDATION ───────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ─── INTERNATIONALIZATION ──────────────────────────────────────────────────────
LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian'),
    ('uz', 'Uzbek'),
]
LANGUAGE_CODE = 'ru'
LOCALE_PATHS = [BASE_DIR / 'locale']
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ─── STATIC FILES (via S3) ─────────────────────────────────────────────────────
# Install: pip install django-storages boto3
AWS_ACCESS_KEY_ID        = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY    = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME  = os.environ['AWS_STORAGE_BUCKET_NAME']
AWS_S3_ENDPOINT_URL      = os.environ['AWS_S3_ENDPOINT_URL']     
AWS_S3_REGION_NAME       = os.environ.get('AWS_S3_REGION_NAME')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE  = 'path'

# Use S3 for static files
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/'

# Local dirs (for collectstatic in dev/fallback)
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ─── MEDIA FILES (local) ──────────────────────────────────────────────────────
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ─── CKEDITOR ─────────────────────────────────────────────────────────────────
CKEDITOR_BASEPATH = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH      = "uploads/"
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 'auto',
        'remove_dialog_tabs': 'image:advanced;link:advanced',
    },
}

# ─── JAZZMIN ───────────────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "site_title": "Elima",
    "site_brand": "Панель управления",
    "welcome_sign": "Elima",
    "site_logo": "img/company_logo_.png",
    "site_header": "Elima Dashboard",
    "show_ui_builder": True,
    "order_with_respect_to": ["pages", "contentmanagement", "store", "blog", "auth"],
    # <<< добавляем вот это
    "custom_css": "admin/css/custom.css",
}

# ─── DEFAULT PK FIELD ─────────────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
